In [199]:
# b <- read.table('../Data/seoul_business.txt' ,header = T, sep = '')
# s <- read.csv('../Data/seoul_sgbs.csv' )
# b <- subset(b, b$동 != '합계' & b$동 != '소계')
# rownames(b) <-c()
# head(b)
# tail(b) # 423 둔촌1동 빼고  ,  여의도동으로 표기되어있음 여의동으로 바꾸기


s <- subset(s, 행정동 != '둔촌1동')
head(s) # 종로5·6가동이 없음 -> 종로5.6가동 으로 표기되어있음 , 여의동으로 되어있음 , 둔촌1동 있음 
tail(s) # 423개
# subset(s , s$행정동 %in% '')
# ifelse(행정동 %in% 동 , 0, as.character(행정동))

  년도 분기 행정동  운영평균 폐업평균 서울운영평균 서울시폐업평균
1 2019 4    둔촌2동 111      49       110          54
3 2019 4    길동    103      47       110          54
4 2019 4    성내3동 110      47       110          54
5 2019 4    성내2동 104      48       110          54
6 2019 4    성내1동 107      51       110          54
7 2019 4    천호3동 108      49       110          54

      년도 분기 행정동     운영평균 폐업평균 서울운영평균 서울시폐업평균
10428 2014 1    무악동      97      53       91           44
10429 2014 1    평창동      95      50       91           44
10430 2014 1    부암동      90      47       91           44
10431 2014 1    삼청동      77      48       91           44
10432 2014 1    사직동     103      50       91           44
10433 2014 1    청운효자동  90      53       91           44

In [174]:
#자치구명 
자치구명 <- c(rep('강동구',17) , rep('송파구',27) , rep('강남구',22) , rep('서초구',18) , rep('관악구',21) , rep('동작구',15) , rep('영등포구',18) , rep('금천구',10) , rep('구로구',15) , rep('강서구',20) , rep('양천구',18) , 
rep('마포구',16) , rep('서대문구',14) , rep('은평구',16) , rep('노원구',19) , rep('도봉구',14) , rep('강북구',13) , rep('성북구',20) , rep('중랑구',16) , rep('동대문구',14) , rep('광진구',15) , 
rep('성동구',17) , rep('용산구',16) , rep('중구',15) , rep('종로구',17))
자치구명 <- as.character(rep(자치구명,4))
#자치구행정동명 <- paste(자치구명, s19$행정동)

In [211]:
final <- data.frame()

In [209]:
s19 <- subset(s , s$년도 == 2019)
s19 <- subset(s19 , s19$서울운영평균 == 110 | s19$서울운영평균 == 109 |s19$서울운영평균 == 108 |s19$서울운영평균 == 107 )
s19 <- data.frame(s19[,1:2] , 자치구행정동명 , s19[,4:7])
s19 <- aggregate( . ~ 자치구행정동명, s19 , mean)
s19 <- s19[,-3]

s18 <- subset(s , s$년도 == 2018)
#s18 <- subset(s18 , s18$서울운영평균 == 102 | s18$서울운영평균 == 109 |s18$서울운영평균 == 108 |s18$서울운영평균 == 107 )
s18 <- data.frame(s18[,1:2] , 자치구행정동명 , s18[,4:7])
s18 <- aggregate( . ~ 자치구행정동명, s18 , mean)
s18 <- s18[,-3]

s17 <- subset(s , s$년도 == 2017)
#s17 <- subset(s17 , s17$서울운영평균 == 110 | s17$서울운영평균 == 109 |s17$서울운영평균 == 108 |s17$서울운영평균 == 107 )
s17 <- data.frame(s17[,1:2] , 자치구행정동명 , s17[,4:7])
s17 <- aggregate( . ~ 자치구행정동명, s17 , mean)
s17 <- s17[,-3]

s16 <- subset(s , s$년도 == 2016)
#s16 <- subset(s16 , s16$서울운영평균 == 110 | s16$서울운영평균 == 109 |s16$서울운영평균 == 108 |s16$서울운영평균 == 107 )
s16 <- data.frame(s16[,1:2] , 자치구행정동명 , s16[,4:7])
s16 <- aggregate( . ~ 자치구행정동명, s16 , mean)
s16 <- s16[,-3]

s15 <- subset(s , s$년도 == 2015)
#s15 <- subset(s15 , s15$서울운영평균 == 110 | s15$서울운영평균 == 109 |s15$서울운영평균 == 108 |s15$서울운영평균 == 107 )
s15 <- data.frame(s15[,1:2] , 자치구행정동명 , s15[,4:7])
s15 <- aggregate( . ~ 자치구행정동명, s15 , mean)
s15 <- s15[,-3]

In [216]:
final <- rbind(s15,s16,s17,s18,s19)
summary(final)
str(final)
head(final)
tail(final)

        자치구행정동명      년도         운영평균         폐업평균
 강남구 개포1동:   5   Min.   :2015   Min.   : 18.75   Min.   : 27.25
 강남구 개포2동:   5   1st Qu.:2016   1st Qu.: 91.50   1st Qu.: 47.00
 강남구 개포4동:   5   Median :2017   Median : 98.75   Median : 49.75
 강남구 논현1동:   5   Mean   :2017   Mean   : 99.53   Mean   : 50.48
 강남구 논현2동:   5   3rd Qu.:2018   3rd Qu.:106.75   3rd Qu.: 53.00
 강남구 대치1동:   5   Max.   :2019   Max.   :170.00   Max.   :147.00
 (Other)       :2085
  서울운영평균    서울시폐업평균
 Min.   : 94.75   Min.   :47.00
 1st Qu.: 95.75   1st Qu.:48.50
 Median : 97.25   Median :49.75
 Mean   : 99.40   Mean   :49.85
 3rd Qu.:100.75   3rd Qu.:50.75
 Max.   :108.50   Max.   :53.25

'data.frame':	2115 obs. of  6 variables:
 $ 자치구행정동명: Factor w/ 423 levels "강남구 개포1동",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ 년도          : num  2015 2015 2015 2015 2015 ...
 $ 운영평균      : num  102 99 98.5 86 87.5 ...
 $ 폐업평균      : num  48.5 48.5 43 43 43.2 ...
 $ 서울운영평균  : num  94.8 94.8 94.8 94.8 94.8 ...
 $ 서울시폐업평균: num  47 47 47 47 47 47 47 47 47 47 ...

  자치구행정동명 년도 운영평균 폐업평균 서울운영평균 서울시폐업평균
1 강남구 개포1동 2015 102.0    48.50    94.75        47
2 강남구 개포2동 2015  99.0    48.50    94.75        47
3 강남구 개포4동 2015  98.5    43.00    94.75        47
4 강남구 논현1동 2015  86.0    43.00    94.75        47
5 강남구 논현2동 2015  87.5    43.25    94.75        47
6 강남구 대치1동 2015  93.0    47.25    94.75        47

     자치구행정동명 년도 운영평균 폐업평균 서울운영평균 서울시폐업평균
2110 중랑구 상봉1동 2019  89.75   49.25    108.5        53.25
2111 중랑구 상봉2동 2019 107.25   50.75    108.5        53.25
2112 중랑구 신내1동 2019  97.00   50.00    108.5        53.25
2113 중랑구 신내2동 2019 100.25   49.00    108.5        53.25
2114 중랑구 중화1동 2019 107.00   51.50    108.5        53.25
2115 중랑구 중화2동 2019 112.00   50.25    108.5        53.25

In [222]:
#write.csv(final, "../Data/seoul_analysis.csv", row.names=F)

In [226]:
a <- read.table("../Data/2015-2019_business_worker.txt" , header =T , sep='' )
colnames(a)

 [1] "년도"
 [2] "자치구명"
 [3] "동"
 [4] "사업체수"
 [5] "총종사자수"
 [6] "총여성종사자수"
 [7] "농업.임업.및.어업"
 [8] "농업.임업.및.어업.여성."
 [9] "광업"
[10] "광업.여성."
[11] "제조업"
[12] "제조업.여성."
[13] "전기.가스.증기.및.공기조절.공급업"
[14] "전기.가스.증기.및.공기조절.공급업.여성."
[15] "수도.하수.및.폐기물.처리.원료.재생업"
[16] "수도.하수.및.폐기물.처리.원료.재생업.여성."
[17] "건설업"
[18] "건설업.여성."
[19] "도매.및.소매업"
[20] "도매.및.소매업.여성."
[21] "운수.및.창고업"
[22] "운수.및.창고업.여성."
[23] "숙박.및.음식점업"
[24] "숙박.및.음식점업.여성."
[25] "정보통신업"
[26] "정보통신업.여성."
[27] "금융.및.보험업"
[28] "금융.및.보험업.여성."
[29] "부동산업"
[30] "부동산업.여성."
[31] "전문.과학.및.기술.서비스업"
[32] "전문.과학.및.기술.서비스업.여성."
[33] "사업시설.관리.사업.지원.및.임대.서비스업"
[34] "사업시설.관리.사업.지원.및.임대.서비스업.여성."
[35] "공공행정.국방.및.사회보장.행정"
[36] "공공행정.국방.및.사회보장.행정.여성."
[37] "교육.서비스업"
[38] "교육.서비스업.여성."
[39] "보건업.및.사회복지.서비스업"
[40] "보건업.및.사회복지.서비스업.여성."
[41] "예술.스포츠.및.여가관련.서비스업"
[42] "예술.스포츠.및.여가관련.서비스업.여성."
[43] "협회.및.단체.수리.및.기타.개인.서비스업"
[44] "협회.및.단체.수리.및.기타.개인.서비스업.여성."